Landing page api data
pacemakerIT/Gachi-backend pull request #4
Opened 2024-10-31 04:12 UTC by mirimkim00

2024-11-03 22:06 UTC, nhistory commented on landing_page/views.py
> +    response_program = supabase.table('Program').select('*').order('status').execute()
여기서 select * 으로 전체 데이터를 다 가져오는 것 보다는 필요한 데이터만 지정하는 것이 더 효율적일 것 같습니다.

2024-11-03 22:06 UTC, nhistory commented on landing_page/views.py
> +    response_mentor = supabase.table('User').select('*, Industry!inner(*)').eq('userTypeId', '74ae0cb7-e4bf-472e-a8a3-e94d895028e5').execute()
위 피드백과 동일합니다.

2024-11-03 22:06 UTC, nhistory commented on landing_page/views.py
> +    response_review = supabase.table('Review').select("*, User!inner(*, Industry!inner(title))").execute()
위 피드백과 동일합니다.

2024-11-03 22:08 UTC, nhistory commented on landing_page/views.py
> +    response_review = supabase.table('Review').select("*, User!inner(*, Industry!inner(title))").execute()
여기서 execute() 함수에서 error가 발생할 때 적절한 status code와 에러 메세지를 반환하는 로직을 추가하면 좋을 것 같습니다.

2024-11-03 22:13 UTC, nhistory commented on landing_page/views.py
> +def landing_page_supabase_connection(request):
landing_page_supabase_connection 함수에서 여러 api를 호출하기 때문에 비동기적으로 구현하는 것이 더 유리해 보입니다. async await 를 사용하면 반응시간에서 개선효과가 있을 것 같습니다.

2024-11-03 22:15 UTC, nhistory requested changes
pytest-django 같은 툴을 사용해서 landing_page_supabase_connection의 테스트 함수를 구현해보면 좋을 것 같습니다. 추후 다른 api가 추가될 때마다 레퍼런스로 활용이 가능할 것 같아요.

2024-11-08 21:33 UTC, ngnlyoosun approved these changes

2024-11-20 02:20 UTC, nhistory approved these changes

2024-11-20 02:20 UTC, merged